name: Check code style

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build
        run: mvn clean install

      - name: Checkstyle
        run: mvn checkstyle:check

      - name: Spotbugs
        run: mvn spotbugs:check

      - name: Syntax Check (if applicable)
        run: mvn compile
