name: Java Syntax Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean compile

      - name: Download Checkstyle
        run: |
          curl -L -o checkstyle-10.4-all.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.4/checkstyle-10.4-all.jar
          # Проверка, что файл был загружен успешно
          if [ ! -f checkstyle-10.4-all.jar ]; then
            echo "Checkstyle JAR file not found!"
            exit 1
          fi

          # Проверка целостности JAR-файла
          if ! java -jar checkstyle-10.4-all.jar -c /sun_checks.xml --help; then
            echo "The JAR file seems to be corrupted or invalid."
            exit 1
          fi

      - name: Run Checkstyle
        run: |
          java -jar checkstyle-10.4-all.jar -c /google_checks.xml src/**/*.java
